name: Battleship
version: '${project.version}'
main: net.quickwrite.battleship.Battleship
api-version: 1.17
authors: [ QuickWrite, Hasenzahn1 ]
description: Battleship for minecraft

depend: [ProtocolLib]

commands:
  mdebug:
    description: Debug Command for testing only
  battleship:
    description: BattleShip Commands for this plugin
  debugGames:
    description: pure Debug Commands